export default {
  "expo": {
    "name": "Ride Share",
    "slug": "Ride-Share",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splashIcon.png",
      "resizeMode": "contain",
      "height": 100,
      "width": 100,
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      // Optional path to the Android file generated by Firebase
      "googleServicesFile": "./android/google-services.json",
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      },
      "package": "com.rideshare"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "plugins": [
      "@react-native-google-signin/google-signin",
      [
        "@rnmapbox/maps",
        {
          "RNMapboxMapsImpl": "maplibre",
          "RNMapboxMapsDownloadToken": process.env.MAPBOX_DOWNLOAD
        }
      ]
    ]
  }
}
